name: Hourly Tests

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        id: tests
        run: |
          pytest | tee pytest.log
        continue-on-error: true
      - name: Send result to Telegram
        if: always()
        run: |
          if [ "${{ steps.tests.outcome }}" == "success" ]; then
            STATUS="PASSED"
          else
            STATUS="FAILED"
          fi
          TEXT="Hourly tests ${STATUS}%0A$(tail -n 20 pytest.log | sed 's/%/%25/g; s/\n/%0A/g; s/\r/%0D/g')"
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" -d chat_id="${CHAT_ID}" -d text="${TEXT}"
